# Generated by Django 4.2.14 on 2024-08-12 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("is_varified", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True,
                        related_name="friends_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_requests_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sent_requests_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
