# Generated by Django 4.2.14 on 2024-08-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_varified",
        ),
        migrations.RemoveField(
            model_name="person",
            name="otp",
        ),
    ]
